---
name: Data-Tabulate
version: 0.05
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: "Table generation!"
license: perl
build_requires:
  Carp: 0
  Test::CheckManifest: 1
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Data::Tabulate:
    file: lib/Data/Tabulate.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
